cooling:
  seed: -1 # -1 means random seed
  epochs: 20_000
  pinn:
    hidden_layers:
    - 100
    - 100
    - 100
    lr: 1.0e-3
    physics_loss_weight: 50.0
    dropout_rate: 0.2


european_call:
  seed: -1 # -1 means random seed
  epochs: 10_000
  pinn:
    hidden_layers:
    - 20
    - 20
    - 20
    lr: 1.0e-3
    physics_loss_weight: 5.0
