nonlinear:
  epochs: 10_000
  pinn:
    hidden_layers:
    - 15
    - 15
    lr: 1.0e-4
    physics_loss_weight: 50.0
    sgld_lr: 1e-4
    lambda_y: 10.0
    lambda_theta: 0.1
  model:
    noise_sd: 0.1
    t_start: 0
    t_end: 10
    t_extend: 10
