nonlinear:
  seed: -1 # -1 means random seed
  epochs: 10_000
  pinn:
    hidden_layers:
    - 15
    - 15
    lr: 1.0e-4
    physics_loss_weight: 0.0
    sgld_lr: 1e-4
    lambda_y: 10.0
    lambda_theta: 0.1
