european_call:
  epochs: 300_000
  eval_freq: -1
  burn: 0.1
  pinn:
    hidden_layers:
    - 50
    - 50
    activation_fn: softplus(beta=10)
    annealing_period: 0.1
    grad_norm_max: -1.0
    lr: 'poly_5e-6_100.0_0.55'
    sgd_momentum: 'linear_0.9_0.0'
    sgld_lr: 'poly_5e-6_100.0_0.55'
    sgld_alpha: 1.0
    lam: 'linear_50.0_1000.0'
    lambda_pde: 1.0
    lambda_theta: 1.0
    encoder_kwargs:
      encoder_hidden_layers:
      - 32
      - 32
      - 8
      encoder_activation: leaky_relu
      prior_sd: 10.0
      sparse_sd: 0.001
      sparsity: 1.0


poisson:
  epochs: 200_000
  eval_freq: -1
  burn: 0.1
  pinn:
    hidden_layers:
    - 50
    - 50
    activation_fn: tanh
    annealing_period: 0.1
    lr: 'poly_2e-6_10.0_0.55'
    sgd_momentum: 'linear_0.9_0.9'
    sgld_lr: 'poly_7e-4_10.0_0.95'
    sgld_alpha: 1.0
    lam: 'log_50.0_500.0'
    lambda_pde: 1.0
    lambda_theta: 1.0
    encoder_kwargs:
      encoder_hidden_layers:
      - 16
      - 16
      - 16
      encoder_activation: leaky_relu
      prior_sd: 10.0


poisson-v2:
  epochs: 200_000
  eval_freq: 1000
  burn: 0.1
  pinn:
    hidden_layers:
    - 50
    - 50
    activation_fn: tanh
    annealing_period: 0.1
    lr: 'poly_2e-6_10.0_0.55'
    sgd_momentum: 'linear_0.9_0.9'
    sgld_lr: 'poly_7e-4_10.0_0.95'
    sgld_alpha: 1.0
    lam: 'linear_50.0_500.0'
    lambda_pde: 1.0
    lambda_theta: 1.0
    encoder_kwargs:
      encoder_hidden_layers:
      - 128
      - 128
      - 12
      encoder_activation: leaky_relu
      prior_sd: 10.0


poisson-nonlinear:
  epochs: 200_000
  eval_freq: 1000
  burn: 0.1
  pinn:
    hidden_layers:
    - 50
    - 50
    activation_fn: tanh
    annealing_period: 0.1
    lr: 'poly_2e-6_10.0_0.55'
    sgd_momentum: 'linear_0.9_0.9'
    sgld_lr: 'poly_7e-4_10.0_0.95'
    sgld_alpha: 1.0
    lam: 'linear_50.0_500.0'
    lambda_pde: 1.0
    lambda_theta: 1.0
    encoder_kwargs:
      encoder_hidden_layers:
      - 64
      - 64
      - 16
      encoder_activation: leaky_relu
      neck_layer_activation: identity
      prior_sd: 10.0

poisson-inverse:
  epochs: 350_000
  eval_freq: 2000
  burn: 0.1
  pinn:
    hidden_layers:
    - 50
    - 50
    activation_fn: tanh
    annealing_period: 0.1
    grad_norm_max: -1.0
    lr: 'poly_2e-6_10.0_0.55'
    sgd_momentum: 'linear_0.9_0.9'
    sgld_lr: 'poly_7e-4_10.0_0.95'
    sgld_alpha: 1.0
    lam: 'linear_10.0_1000.0'
    lambda_pde: 1.0
    lambda_theta: 1.0
    encoder_kwargs:
      encoder_hidden_layers:
      - 128
      - 128
      - 12
      encoder_activation: leaky_relu
      prior_sd: 10.0


poisson-2d:
  epochs: 200_000
  eval_freq: 2000
  burn: 0.1
  pinn:
    hidden_layers:
    - 50
    - 50
    activation_fn: silu
    annealing_period: 0.1
    grad_norm_max: -1.0
    lr: 'poly_0.5e-6_10.0_0.55'
    sgd_momentum: 'linear_0.9_0.9'
    sgld_lr: 'poly_2.5e-4_10.0_0.55'
    sgld_alpha: 'linear_0.1_1.0'
    lam: 'log_50.0_1000.0'
    lambda_pde: 0.1
    lambda_theta: 1.0
    encoder_kwargs:
      encoder_hidden_layers:
      - 512
      - 512
      - 16
      encoder_activation: leaky_relu
      prior_sd: 10.0
  

linear-1d:
  epochs: 400_000
  eval_freq: 4000
  burn: 0.1
  pinn:
    hidden_layers:
    - 30
    - 30
    activation_fn: tanh
    annealing_period: 0.1
    lr: 'poly_3e-6_10.0_0.55'
    sgd_momentum: 'linear_0.9_0.9'
    sgld_lr: 'poly_7e-4_10.0_0.95'
    sgld_alpha: 1.0
    lam: 'log_10.0_100.0'
    lambda_pde: 1.0
    lambda_theta: 1.0
    encoder_kwargs:
      encoder_hidden_layers:
      - 16
      - 16
      - 4
      encoder_activation: leaky_relu
      prior_sd: 10.0


montroll:
  epochs: 500_000
  eval_freq: 2000
  burn: 0.3
  pinn:
    positive_output: True
    hidden_layers:
    - 50
    - 50
    activation_fn: softplus(beta=10)
    annealing_period: 0.2
    lr: 'poly_1e-6_10.0_0.55'
    sgd_momentum: 'linear_0.9_0.99'
    sgld_lr: 'poly_1e-4_10.0_0.95'
    sgld_alpha: 1.0
    lam: 'log_50.0_500.0'
    lambda_pde: 'linear_0.0_1.0'
    lambda_theta: 1.0
    encoder_kwargs:
      encoder_hidden_layers:
      - 32
      - 32
      - 16
      encoder_activation: leaky_relu
      prior_sd: 10.0