cooling:
  epochs: 10_000
  pinn:
    hidden_layers:
    - 15
    - 15
    activation_fn: softplus(beta=5)
    lr: 1.0e-3
    physics_loss_weight: 50.0


european_call:
  epochs: 20_000
  pinn:
    hidden_layers:
    - 20
    - 20
    - 20
    activation_fn: softplus(beta=5)
    lr: 1.0e-3
    physics_loss_weight: 10.0

