poisson-nonlinear:
  epochs: 100_000
  eval_freq: -1
  burn: 0.5
  pinn:
    hidden_layers:
    - 30
    - 30
    activation_fn: tanh
    lr: 3e-4
    lambda_pde: 1.0
    dropout_rate: 0.005


poisson-inverse:
  epochs: 20_000
  eval_freq: -1
  burn: 0.5
  pinn:
    hidden_layers:
    - 30
    - 30
    activation_fn: tanh
    lr: 3e-4
    lambda_pde: 1.0
    dropout_rate: 0.005
