cooling:
  n_samples: 200
  epochs: 10_000
  pinn:
    hidden_layers:
    - 20
    - 20
    activation_fn: softplus(beta=5)
    lr: 1.0e-3
    physics_loss_weight: 50.0


european_call:
  n_samples: 200
  epochs: 20_000
  pinn:
    hidden_layers:
    - 20
    - 20
    - 20
    activation_fn: softplus(beta=5)
    lr: 1.0e-3
    physics_loss_weight: 10.0

poisson:
  n_samples: 16
  epochs: 10_000
  pinn:
    hidden_layers:
    - 50
    - 50
    activation_fn: tanh
    lr: 1.0e-3
    physics_loss_weight: 10.0

