cooling:
  epochs: 10_000
  pinn:
    hidden_layers:
    - 50
    - 50
    lr: 1.0e-3
    physics_loss_weight: 50.0
    kl_weight: 1.0
  model:
    Tenv: 25
    T0: 100
    R: 0.005
    t_end: 300
    t_extend: 1500
    noise_sd: 1.0


european_call:
  epochs: 10_000
  pinn:
    hidden_layers:
    - 20
    - 20
    - 20
    lr: 1.0e-3
    physics_loss_weight: 5.0
  model:
    S_range:
    - 0
    - 160
    t_range:
    - 0
    - 1
    sigma: 0.5
    r: 0.05
    K: 80
    noise_sd: 1.0
