cooling:
  n_samples: 200
  epochs: 10_000
  pinn:
    hidden_layers:
    - 20
    - 20
    activation_fn: softplus(beta=5)
    lr: 1.0e-3
    lambda_pde: 50.0


european_call:
  epochs: 200_000
  eval_freq: 1000
  burn: 0.5 
  pinn:
    hidden_layers:
    - 20
    - 20
    - 20
    activation_fn: softplus(beta=5)
    lr: 1.0e-3
    lambda_pde: 10.0


poisson:
  epochs: 100_000
  eval_freq: -1
  burn: 0.5
  pinn:
    hidden_layers:
    - 30
    - 30
    activation_fn: tanh
    lr: 3e-4
    lambda_pde: 1.0
    dropout_rate: 0.005


poisson-v2:
  epochs: 100_000
  eval_freq: -1
  burn: 0.5
  pinn:
    hidden_layers:
    - 30
    - 30
    activation_fn: tanh
    lr: 3e-4
    lambda_pde: 1.0
    dropout_rate: 0.005


poisson-nonlinear:
  epochs: 100_000
  eval_freq: -1
  burn: 0.5
  pinn:
    hidden_layers:
    - 30
    - 30
    activation_fn: tanh
    lr: 3e-4
    lambda_pde: 1.0
    dropout_rate: 0.005


poisson-2d:
  epochs: 200_000
  eval_freq: -1
  burn: 0.5
  pinn:
    hidden_layers:
    - 50
    - 50
    activation_fn: tanh
    lr: 3e-4
    lambda_pde: 1.0
    dropout_rate: 0.0


nonlinear:
  epochs: 10_000
  pinn:
    hidden_layers:
    - 30
    - 30
    activation_fn: tanh
    lr: 1.0e-3
    lambda_pde: 0.0

