montroll:
  epochs: 200_000
  eval_freq: 2000
  burn: 0.1
  pinn:
    positive_output: True
    hidden_layers:
    - 50
    - 50
    activation_fn: softplus(beta=10)
    annealing_period: 0.1
    lr: 'poly_2e-6_10.0_0.55'
    sgd_momentum: 'linear_0.9_0.9'
    sgld_lr: 'poly_5e-4_10.0_0.95'
    sgld_alpha: 1.0
    lam: 'log_50.0_500.0'
    lambda_pde: 'linear_0.0_1.0'
    lambda_theta: 1.0
    encoder_kwargs:
      encoder_hidden_layers:
      - 16
      - 8
      - 4
      encoder_activation: leaky_relu
      prior_sd: 10.0
  
montroll_theta:
  epochs: 200_000
  eval_freq: 2000
  burn: 0.1
  pinn:
    positive_output: True
    hidden_layers:
    - 50
    - 50
    activation_fn: softplus(beta=10)
    annealing_period: 0.1
    lr: 'poly_1e-6_10.0_0.55'
    sgd_momentum: 'linear_0.9_0.99'
    sgld_lr: 'poly_1e-4_10.0_0.95'
    sgld_alpha: 1.0
    lam: 'log_50.0_500.0'
    lambda_pde: 'linear_0.0_1.0'
    lambda_theta: 1.0
    encoder_kwargs:
      encoder_hidden_layers:
      - 32
      - 32
      - 16
      encoder_activation: leaky_relu
      prior_sd: 10.0
  
montroll_fixed:
  epochs: 200_000
  eval_freq: 2000
  burn: 0.3
  pinn:
    positive_output: True
    hidden_layers:
    - 50
    - 50
    activation_fn: softplus(beta=10)
    annealing_period: 0.2
    lr: 'poly_1e-6_10.0_0.55'
    sgd_momentum: 'linear_0.9_0.99'
    sgld_lr: 'poly_1e-4_10.0_0.95'
    sgld_alpha: 1.0
    lam: 'log_50.0_500.0'
    lambda_pde: 'linear_0.0_1.0'
    lambda_theta: 1.0
    encoder_kwargs:
      encoder_hidden_layers:
      - 32
      - 32
      - 16
      encoder_activation: leaky_relu
      prior_sd: 10.0
