cooling:
  seed: -1 # -1 means random seed
  epochs: 10_000
  pinn:
    hidden_layers:
    - 15
    - 15
    lr: 1.0e-3
    physics_loss_weight: 50.0


european_call:
  seed: -1 # -1 means random seed
  epochs: 20_000
  pinn:
    hidden_layers:
    - 20
    - 20
    - 20
    lr: 1.0e-3
    physics_loss_weight: 10.0

