cooling:
  seed: -1 # -1 means random seed
  epochs: 10_000
  pinn:
    hidden_layers:
    - 20
    - 20
    lr: 1.0e-5
    physics_loss_weight: 50.0
    sgld_lr: 1e-4
    lambda_y: 1.0
    lambda_theta: 1.0



european_call:
  seed: -1 # -1 means random seed
  epochs: 20_000
  pinn:
    hidden_layers:
    - 20
    - 20
    - 20
    lr: 1.0e-4
    physics_loss_weight: 10.0
    sgld_lr: 1e-4
    lambda_y: 10.0
    lambda_theta: 0.1
