poisson:
  epochs: 200_000
  eval_freq: 2000
  burn: 0.1
  pinn:
    hidden_layers:
    - 50
    - 50
    activation_fn: tanh
    annealing_period: 0.1
    lr: 'poly_2e-6_10.0_0.55'
    sgd_momentum: 'linear_0.9_0.9'
    sgld_lr: 'poly_5e-4_10.0_0.95'
    sgld_alpha: 'linear_0.1_1.0'
    lam: 'log_10.0_500.0'
    lambda_pde: 1.0
    lambda_theta: 1.0
    encoder_kwargs:
      encoder_hidden_layers:
      - 16
      - 8
      - 4
      encoder_activation: leaky_relu
      prior_sd: 10.0


poisson-inverse:
  epochs: 200_000
  eval_freq: 2000
  burn: 0.1
  pinn:
    hidden_layers:
    - 50
    - 50
    activation_fn: tanh
    annealing_period: 0.1
    grad_norm_max: -1.0
    lr: 'poly_2e-6_10.0_0.55'
    sgd_momentum: 'linear_0.9_0.9'
    sgld_lr: 'poly_5e-4_10.0_0.95'
    sgld_alpha: 'linear_0.1_1.0'
    lam: 'linear_10.0_1000.0'
    lambda_pde: 1.0
    lambda_theta: 1.0
    encoder_kwargs:
      encoder_hidden_layers:
      - 16
      - 8
      - 4
      encoder_activation: leaky_relu
      prior_sd: 10.0

