cooling:
  n_samples: 200
  epochs: 10_000
  pinn:
    hidden_layers:
    - 20
    - 20
    activation_fn: softplus(beta=10)
    lr: 1.0e-5
    lambda_pde: 50.0
    sgld_lr: 1e-4
    lambda_y: 1.0
    lambda_theta: 0.1
    encoder_kwargs:
      encoder_activation: softplus(beta=10)
      prior_sd: 0.1
      sparse_threshold: 0.01

european_call:
  n_samples: 200
  epochs: 20_000
  pinn:
    hidden_layers:
    - 20
    - 20
    - 20
    activation_fn: softplus(beta=10)
    lr: 1.0e-5
    lambda_pde: 10.0
    sgld_lr: 1e-4
    lambda_y: 10.0
    lambda_theta: 0.1
    encoder_kwargs:
      encoder_activation: relu
      prior_sd: 1.0
      sparse_threshold: 0.01


nonlinear:
  n_samples: 200
  epochs: 10_000
  pinn:
    hidden_layers:
    - 15
    - 15
    activation_fn: softplus(beta=10)
    lr: 1.0e-4
    lambda_pde: 0.0
    sgld_lr: 1e-4
    lambda_y: 20.0
    lambda_theta: 0.2
    encoder_kwargs:
      encoder_activation: softplus(beta=10)
      prior_sd: 0.5
      sparse_threshold: 0.01

poisson:
  n_samples: 200
  epochs: 15_000
  pinn:
    hidden_layers:
    - 30
    - 30
    activation_fn: tanh
    lr: 1.0e-4
    lambda_pde: 'lin_0.5_1.0'
    sgld_lr: 1.0e-4
    lambda_y: 1.0
    lambda_theta: 10.0
    pretrain_epochs: 5_000
    encoder_kwargs:
      encoder_activation: leaky_relu
      prior_sd: 1.0
      sparse_threshold: 0.01